# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nsyv3aIduJlS2W1l9ura_0SvPtwr6gv
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sample dataset: Titanic (available in Seaborn)
df = sns.load_dataset("titanic")

# 1. Distribution: Age of passengers
plt.figure(figsize=(8,5))
sns.histplot(df['age'].dropna(), bins=30, kde=True)
plt.title("Distribution of Passenger Ages")
plt.show()

# 2. Comparison: Survival count by gender
plt.figure(figsize=(6,4))
sns.countplot(x='sex', hue='survived', data=df)
plt.title("Survival Rate by Gender")
plt.show()

# 3. Relationship: Age vs Fare
plt.figure(figsize=(8,6))
sns.scatterplot(x='age', y='fare', hue='class', data=df)
plt.title("Age vs Fare Paid (by Class)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Load dataset
df = sns.load_dataset("titanic")

# Clean data (remove missing values where necessary)
df = df.dropna(subset=["age", "fare", "class", "sex", "survived"])

# 1. Overall Survival Count
plt.figure(figsize=(6,4))
sns.countplot(x="survived", data=df, palette="viridis")
plt.title("Overall Survival Count")
plt.xlabel("0 = Did Not Survive, 1 = Survived")
plt.show()

# 2. Survival by Gender
plt.figure(figsize=(6,4))
sns.countplot(x="sex", hue="survived", data=df, palette="Set2")
plt.title("Survival by Gender")
plt.show()

#3. Survival by Class
plt.figure(figsize=(6,4))
sns.countplot(x="class", hue="survived", data=df, palette="Set1")
plt.title("Survival by Passenger Class")
plt.show()

# 4. Age Distribution by Survival
plt.figure(figsize=(8,5))
sns.histplot(data=df, x="age", hue="survived", bins=30, kde=True, palette="coolwarm")
plt.title("Age Distribution of Survivors vs Non-Survivors")
plt.show()

# 5. Fare Distribution by Class
plt.figure(figsize=(8,5))
sns.boxplot(x="class", y="fare", data=df, palette="pastel")
plt.title("Fare Distribution by Class")
plt.show()